config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  resources :carriers

  resources :suggestions do
    get :autocomplete_account_name, :on => :collection
  end

  devise_for :users

devise_scope :user do
  get 'register', to: 'devise/registrations#new', as: :register
  get 'login', to: 'devise/sessions#new', as: :login
  get 'logout', to: 'devise/sessions#destroy', as: :logout
end

  get 'board', to: 'loads#index', as: :board

  resources :loads

   root 'loads#index'

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
	belongs_to :user
	has_many :bookings
	#has_one :booking_history, through :bookings
	#has_many :loads, through :bookings
	accepts_nested_attributes_for :bookings
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :set_carrier, only: [:show, :edit, :update, :destroy]

  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.all
  end

  # GET /carriers/1
  # GET /carriers/1.json
  def show_loads
  		@carrier = carrier.find_by_mc(params[:id])
  			if @carriers
  				@loads = @carrier.loads.all
  				render action: :show
  			else
  				render file: 'public/404', status: 404, formats: [:html]
  			end
  end

  # GET /carriers/new
  def new
    @carrier = Carrier.new
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = Carrier.new(carrier_params)

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to @carrier, notice: 'Carrier was successfully created.' }
        format.json { render :show, status: :created, location: @carrier }
      else
        format.html { render :new }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1
  # PATCH/PUT /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier.destroy
    respond_to do |format|
      format.html { redirect_to carriers_url, notice: 'Carrier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrier_params
      params.require(:carrier).permit(:name, :mc_no, :dot_no, 
                                      :user_id, :account_id)
    end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/views/carriers/_form.html.erb
<%= simple_form_for(@carrier) do |f| %>
	<% if @carrier.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@carrier.errors.count, "error") %> prohibited this carrier from being saved:</h2>

			<ul>
				<% @carrier.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <%= f.error_notification %>

  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :name %>
  <%= f.input :mc_no %>
  <%= f.input :dot_no %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carriers/edit.html.erb
<h1>Editing carrier</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrier %> |
<%= link_to 'Back', carriers_path %>

app/views/carriers/index.html.erb
<h1>Your Carriers</h1>

<%= link_to 'New Carrier', new_carrier_path, class: "btn btn-default" %>

<% @carriers.each do |carrier| %>
  <div class="carrier">
    <strong><%= link_to carrier.name, carrier %></strong>
    <p><%= carrier.phone_number %></p>
  </div>
  <div class="meta">
    <%= link_to time_ago_in_words(carrier.created_at) + "ago", carrier %>
    <span class="admin">
      | <%= link_to 'Edit', edit_carrier_path(carrier) %>| 
     <%= link_to 'Delete', carrier, method: :delete, data: {confirm: "Are you sure you want to delete this carrier?"} %>
    </span>
  </div>
<% end %>

app/views/carriers/new.html.erb
<h1>New carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carrier.name %>
</p>

<p>
  <strong>Md:</strong>
  <%= @carrier.md %>
</p>

<%= link_to 'Edit', edit_carrier_path(@carrier) %> |
<%= link_to 'Back', carriers_path %>