config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  resources :carriers

  resources :suggestions do
    get :autocomplete_account_name, :on => :collection
  end

  devise_for :users

devise_scope :user do
  get 'register', to: 'devise/registrations#new', as: :register
  get 'login', to: 'devise/sessions#new', as: :login
  get 'logout', to: 'devise/sessions#destroy', as: :logout
end

  get 'board', to: 'loads#index', as: :board

  resources :loads

   root 'loads#index'

end

app/models/load.rb
class Load < ActiveRecord::Base
	belongs_to :user
	has_many :bookings
	has_many :carriers, through: :bookings
	accepts_nested_attributes_for :bookings
	accepts_nested_attributes_for :carriers

	validates :origin, presence: true
	validates :destination, presence: true
	validates :pick_date, presence: true
	validates :drop_date, presence: true
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :set_load, only: [:show, :edit, :update, :destroy, :add_carrier]
  before_action :authenticate_user!, only: [:new, :create]
  # GET /loads
  # GET /loads.json
  def index
    @loads = Load.all
  end

  # GET /loads/1
  # GET /loads/1.json
  def show
  end

  # GET /loads/new
  def new
    @load = Load.new
  end

  # GET /loads/1/edit
  def edit
  end

  # POST /loads
  # POST /loads.json
  def create
    @load = Load.new(load_params)

    respond_to do |format|
      if @load.save
        format.html { redirect_to @load, notice: 'Load was successfully created.' }
        format.json { render :show, status: :created, location: @load }
      else
        format.html { render :new }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_carrier
  end

  # PATCH/PUT /loads/1
  # PATCH/PUT /loads/1.json
  def update
    respond_to do |format|
      if @load.update(load_params)
        format.html { redirect_to @load, notice: 'Load was successfully updated.' }
        format.json { render :show, status: :ok, location: @load }
      else
        format.html { render :edit }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loads/1
  # DELETE /loads/1.json
  def destroy
    @load.destroy
    respond_to do |format|
      format.html { redirect_to loads_url, notice: 'Load was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = Load.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def load_params
      params.require(:load).permit(:origin, :destination, :user_id,
                                   :carrier_id, :pick_date, :pick_time,
                                   :drop_date, :drop_time, :account_id)
    end
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/views/loads/_form.html.erb
<%= simple_form_for(@load) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :origin %>
    <%= f.input :pick_date %>
   	<%= f.input :pick_time %>
    <%= f.input :destination %>
    <%= f.input :drop_date %>
    <%= f.input :drop_time %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/loads/edit.html.erb
<h1>Editing load</h1>

<%= render 'form' %>

<%= link_to 'Show', @load %> |
<%= link_to 'Back', loads_path %>

app/views/loads/index.html.erb
<h1 id="navbar" class="page-header">Loads</h1>

<%= link_to 'New Load', new_load_path, class: "btn btn-default" %>

<% @loads.each do |load| %>
  <div class="load">
    <strong><%= load.origin %></strong>
    <p><%= load.pick_date %><%= load.pick_time %></p>
    <strong><%= load.destination %></strong>
    <p><%= load.drop_date %><%= load.drop_time %></p>
  </div>
  <div class="meta">
    <%= link_to time_ago_in_words(load.created_at) + "ago", load %>
    <span class="admin">
      | <%= link_to 'Edit', edit_load_path(load) %>| 
     <%= link_to 'Delete', load, method: :delete, data: {confirm: "Are you sure you want to delete this load?"} %>
    </span>
  </div>
<% end %>

app/views/loads/new.html.erb
<h1>New load</h1>

<%= render 'form' %>

<%= link_to 'Back', loads_path %>

app/views/loads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @load.origin %>
</p>

<p>
	<strong>Pickup:</strong>
	<%= @load.pick_date %>, <%= @load.pick_time %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @load.destination %>
</p>

<p>
	<strong>Delivery:</strong>
	<%= @load.drop_date %>, <%= @load.drop_time %>
</p>

<%= link_to 'Edit', edit_load_path(@load) %> |
<%= link_to 'Back', loads_path %>