config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  resources :carriers

  resources :suggestions do
    get :autocomplete_account_name, :on => :collection
  end

  devise_for :users

devise_scope :user do
  get 'register', to: 'devise/registrations#new', as: :register
  get 'login', to: 'devise/sessions#new', as: :login
  get 'logout', to: 'devise/sessions#destroy', as: :logout
end

  get 'board', to: 'loads#index', as: :board

  resources :loads

   root 'loads#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freightrunner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header pull-left">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class+"icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">FreightRunner</a>
		</div>
		<div class="navbar-header pull-right">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
					<li><%= link_to "log Out", logout_path %></li>
				<% else %>
					<li><%= link_to 'Log in', login_path %></li>
					<li><%= link_to 'Register', new_user_registration_path %></li>
				<% end %>
			</ul>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">My Board</a></li>
				<li><%= link_to "Carriers", carriers_path %></li>
			</ul>
		</div>
	</div>
</nav>

	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %> alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<%= message %>
			</div>
		<% end %>
		<%= yield %>
	</div>

	
</body>
</html>